spring:
  application:
    name: hr-gateway
  cloud:
    gateway:
      routes:
        # Rota para o serviço HR-PAYROLL
        - id: hr-payroll
          uri: lb://HR-PAYROLL
          predicates:
            - Path=/hr-payroll/**
          filters:
            - RewritePath=/hr-payroll/(?<segment>.*), /${segment}
            
        # Rota para o serviço HR-WORKER
        - id: hr-worker
          uri: lb://HR-WORKER 
          predicates:
            - Path=/hr-worker/**
          filters:
            - RewritePath=/hr-worker/(?<segment>.*), /${segment}
                        
        # Rota para o serviço HR-USER
        - id: hr-user
          uri: lb://HR-USER
          predicates:
            - Path=/hr-user/**
          filters:
            - RewritePath=/hr-user/(?<segment>.*), /${segment}            
            
        # Rota para o serviço HR-OAUTH
        - id: hr-oauth 
          uri: lb://HR-OAUTH
          predicates:
            - Path=/hr-oauth/**
          filters:
            - RewritePath=/hr-oauth/(?<segment>.*), /${segment}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    
server:
  port: 8000