spring:
  application:
    name: hr-gateway
  cloud:
    gateway:
      routes:
        - id: hr-payroll
          uri: lb://HR-PAYROLL
          predicates:
            - Path=/hr-payroll/** 
          filters:
            - RewritePath=/hr-payroll/(?<segment>.*), /${segment}
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
server:
  port: 8000